# create a default administrator
puts "criando administrador padrão..."
Administrator.create!(name: "Administrator", email: "admin@email.com", password: "administrator", password_confirmation: "administrator")

puts "criando generos..."
Gender.create(name: "Masculino", description: "")
Gender.create(name: "Feminino", description: "")

puts "criando grupos de transtornos..."
DisorderGroup.create(name: "Transtornos de Neurodesenvolvimento", description: "")
DisorderGroup.create(name: "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", description: "")
DisorderGroup.create(name: "Transtorno Bipolar e Seus Correlatos", description: "")
DisorderGroup.create(name: "Transtornos Depressivos", description: "")
DisorderGroup.create(name: "Transtornos de Ansiedade", description: "")
DisorderGroup.create(name: "Transtorno Obsessivo-Compulsivo e Seus Correlatos", description: "")
DisorderGroup.create(name: "Transtorno Traumático e de Estresse e Seus Correlatos", description: "")
DisorderGroup.create(name: "Transtornos Dissociativos", description: "")
DisorderGroup.create(name: "Transtornos Somáticos-Sintomáticos", description: "")
DisorderGroup.create(name: "Alimentação e Transtornos Alimentares", description: "")
DisorderGroup.create(name: "Transtornos de Eliminação", description: "")
DisorderGroup.create(name: "Transtornos do Sono e do Despertar (Sono-Vigília)", description: "")
DisorderGroup.create(name: "Disfunções Sexuais", description: "")
DisorderGroup.create(name: "Disforia de Gênero", description: "")
DisorderGroup.create(name: "Transtornos de Conduta, de Controle do Impulso e da Disrupção", description: "")
DisorderGroup.create(name: "Transtornos de Adição e de Uso de Substâncias", description: "")
DisorderGroup.create(name: "Transtornos Neurocognitivos", description: "")
DisorderGroup.create(name: "Transtornos da Personalidade18. Transtornos da Personalidade", description: "")
DisorderGroup.create(name: "Transtornos de Parafilias (Parafílicos)", description: "")
DisorderGroup.create(name: "Outros Transtornos Mentais", description: "")

puts "criando transtornos..."
Disorder.create(name: "Transtornos do Desenvolvimento Intelectual", description: "", disorder_group_id: 1)
Disorder.create(name: "Transtornos de Comunicação", description: "", disorder_group_id: 1)
Disorder.create(name: "Transtorno do Espectro Autista", description: "", disorder_group_id: 1)
Disorder.create(name: "Transtorno de Déficit de Atenção/Hiperatividade", description: "", disorder_group_id: 1)
Disorder.create(name: "Transtorno de Aprendizagem Específica", description: "", disorder_group_id: 1)
Disorder.create(name: "Transtornos Motores", description: "", disorder_group_id: 1)

Disorder.create(name: "Transtorno da Personalidade Esquizotípica", description: "", disorder_group_id: 2)
Disorder.create(name: "Transtorno Delirante", description: "", disorder_group_id: 2)
Disorder.create(name: "Transtorno Psicótico Breve", description: "", disorder_group_id: 2)
Disorder.create(name: "Transtorno Psicótico Induzido por Substância", description: "", disorder_group_id: 2)
Disorder.create(name: "Transtorno Psicótico Associado à Outra Condição Médica", description: "", disorder_group_id: 2)
Disorder.create(name: "Transtorno Catatônico Associado à Outra Condição Médica", description: "", disorder_group_id: 2)
Disorder.create(name: "Transtorno Esquizofreniforme", description: "", disorder_group_id: 2)
Disorder.create(name: "Transtorno Esquizoafetivo", description: "", disorder_group_id: 2)
Disorder.create(name: "Esquizofrenia", description: "", disorder_group_id: 2)
Disorder.create(name: "Transtorno Psicótico Sem Outra Especificação", description: "", disorder_group_id: 2)
Disorder.create(name: "Transtorno Catatônico Sem Outra Especificação", description: "", disorder_group_id: 2)

Disorder.create(name: "Transtorno Bipolar I", description: "", disorder_group_id: 3)
Disorder.create(name: "Transtorno Bipolar II", description: "", disorder_group_id: 3)
Disorder.create(name: "Transtorno Ciclotímico", description: "", disorder_group_id: 3)
Disorder.create(name: "Transtorno Bipolar Induzido por Substâncias", description: "", disorder_group_id: 3)
Disorder.create(name: "Transtorno Bipolar Associado com Outra Condição Médica", description: "", disorder_group_id: 3)
Disorder.create(name: "Transtorno Bipolar Sem Outra Especificação", description: "", disorder_group_id: 3)

Disorder.create(name: "Transtorno da Desregulação da Disrupção do Humor", description: "", disorder_group_id: 4)
Disorder.create(name: "Transtorno Depressivo Maior - Episódio Único", description: "", disorder_group_id: 4)
Disorder.create(name: "Transtorno Depressivo Maior - Recorrente", description: "", disorder_group_id: 4)
Disorder.create(name: "Transtorno Distímico", description: "", disorder_group_id: 4)
Disorder.create(name: "Transtorno Disfórico Pré-Menstrual", description: "", disorder_group_id: 4)
Disorder.create(name: "Transtorno Depressivo Induzido por Substâncias", description: "", disorder_group_id: 4)
Disorder.create(name: "Transtorno Depressivo Associado à Outra Condição Médica ", description: "", disorder_group_id: 4)
Disorder.create(name: "Transtorno Depressivo Sem Outra Especificação", description: "", disorder_group_id: 4)

Disorder.create(name: "Transtorno de Ansiedade de Separação", description: "", disorder_group_id: 5)
Disorder.create(name: "Transtorno de Pânico", description: "", disorder_group_id: 5)
Disorder.create(name: "Agorafobia", description: "", disorder_group_id: 5)
Disorder.create(name: "Fobia Específica", description: "", disorder_group_id: 5)
Disorder.create(name: "Transtorno de Ansiedade Social (Fobia Social)", description: "", disorder_group_id: 5)
Disorder.create(name: "Transtorno de Ansiedade Generalizada", description: "", disorder_group_id: 5)
Disorder.create(name: "Transtorno de Ansiedade Induzida por Substância", description: "", disorder_group_id: 5)
Disorder.create(name: "Transtorno de Ansiedade Associado à Outra Condição Médica", description: "", disorder_group_id: 5)
Disorder.create(name: "Transtorno de Ansiedade Sem Outra Especificação", description: "", disorder_group_id: 5)

Disorder.create(name: "Transtorno Obsessivo-Compulsivo", description: "", disorder_group_id: 6)
Disorder.create(name: "Transtorno Dismórfico Corporal", description: "", disorder_group_id: 6)
Disorder.create(name: "Transtorno de Acumulação", description: "", disorder_group_id: 6)
Disorder.create(name: "Transtorno de Puxar-Cabelo", description: "", disorder_group_id: 6)
Disorder.create(name: "Transtorno de Escarificação", description: "", disorder_group_id: 6)
Disorder.create(name: "Transtorno Obsessivo-Compulsivo Induzido por Substâncias ou Transtornos Correlatos", description: "", disorder_group_id: 6)
Disorder.create(name: "Transtorno Obsessivo-Compulsivo Sem Outra Especificação ou Transtornos Correlatos", description: "", disorder_group_id: 6)

Disorder.create(name: "Transtorno de Vinculação Reativa", description: "", disorder_group_id: 7)
Disorder.create(name: "Transtorno de Compromisso Social Desinibido", description: "", disorder_group_id: 7)
Disorder.create(name: "Transtorno de Stress Agudo", description: "", disorder_group_id: 7)
Disorder.create(name: "Transtorno de Stress Pós-Traumático", description: "", disorder_group_id: 7)
Disorder.create(name: "Transtornos de Ajustamento", description: "", disorder_group_id: 7)
Disorder.create(name: "Transtorno Traumático ou de Stress Sem Outra Especificação e Seus Correlatos", description: "", disorder_group_id: 7)

Disorder.create(name: "Transtorno de Despersonalização-Desrealização", description: "", disorder_group_id: 8)
Disorder.create(name: "Amnésia Dissociativa", description: "", disorder_group_id: 8)
Disorder.create(name: "Transtorno Dissociativo de Identidade", description: "", disorder_group_id: 8)
Disorder.create(name: "Transtorno Dissociativo Sem Outra Especificação", description: "", disorder_group_id: 8)

Disorder.create(name: "Transtornos Somáticos-Sintomáticos", description: "", disorder_group_id: 9)
Disorder.create(name: "Transtorno Hipocondríaco Ansioso", description: "", disorder_group_id: 9)
Disorder.create(name: "Transtorno Conversivo", description: "", disorder_group_id: 9)
Disorder.create(name: "Fatores Psicológicos Afetados por uma Condição Médica", description: "", disorder_group_id: 9)
Disorder.create(name: "Transtorno Factício", description: "", disorder_group_id: 9)
Disorder.create(name: "Transtorno Somático-Sintomático Sem Outra Especificação", description: "", disorder_group_id: 9)

Disorder.create(name: "Lambiscar (Picar)", description: "", disorder_group_id: 10)
Disorder.create(name: "Transtorno de Ruminação", description: "", disorder_group_id: 10)
Disorder.create(name: "Transtorno de Ingestão Alimentar Restritiva ou de Impedimento", description: "", disorder_group_id: 10)
Disorder.create(name: "Anorexia Nervosa", description: "", disorder_group_id: 10)
Disorder.create(name: "Bulimia Nervosa", description: "", disorder_group_id: 10)
Disorder.create(name: "Transtorno de Compulsão Alimentar Periódica", description: "", disorder_group_id: 10)
Disorder.create(name: "Transtorno Alimentar Sem Outra Classificação", description: "", disorder_group_id: 10)

Disorder.create(name: "Enurese", description: "", disorder_group_id: 11)
Disorder.create(name: "Encoprese", description: "", disorder_group_id: 11)

Disorder.create(name: "Transtorno de Insônia", description: "", disorder_group_id: 12)
Disorder.create(name: "Transtorno de Hipersonolência", description: "", disorder_group_id: 12)
Disorder.create(name: "Deficiência Narcolepsia/Hiprocretina", description: "", disorder_group_id: 12)
Disorder.create(name: "Síndrome de Sono Obstruído - Apneia, Hipopneia", description: "", disorder_group_id: 12)
Disorder.create(name: "Apneia Central do Sono", description: "", disorder_group_id: 12)
Disorder.create(name: "Hipoventilação Relacionada com o Sono", description: "", disorder_group_id: 12)
Disorder.create(name: "Transtorno do Ritmo Circadiano do Sono e do Despertar", description: "", disorder_group_id: 12)
Disorder.create(name: "Transtorno do Levantar", description: "", disorder_group_id: 12)
Disorder.create(name: "Transtorno de Pesadelo", description: "", disorder_group_id: 12)
Disorder.create(name: "Transtorno do Comportamento do Movimento Rápido dos Olhos (REM) no Sono", description: "", disorder_group_id: 12)
Disorder.create(name: "Transtorno das Pernas Inquietas", description: "", disorder_group_id: 12)
Disorder.create(name: "Transtorno do Sono Induzido por Substâncias", description: "", disorder_group_id: 12)

Disorder.create(name: "Transtorno da Ereção", description: "", disorder_group_id: 13)
Disorder.create(name: "Transtorno Orgástico Feminino", description: "", disorder_group_id: 13)
Disorder.create(name: "Ejaculação Atrasada", description: "", disorder_group_id: 13)
Disorder.create(name: "Ejaculação Precoce", description: "", disorder_group_id: 13)
Disorder.create(name: "Transtorno Feminino do Interesse/Excitação Sexual", description: "", disorder_group_id: 13)
Disorder.create(name: "Transtorno Masculino do Desejo Sexual Hipoativo", description: "", disorder_group_id: 13)
Disorder.create(name: "Transtorno da Penetração Pélvico-Genital Dolorosa", description: "", disorder_group_id: 13)
Disorder.create(name: "Disfunção Sexual Induzida por Substância/Medicação", description: "", disorder_group_id: 13)
Disorder.create(name: "Disfunção Sexual Sem Outra Especificação", description: "", disorder_group_id: 13)

Disorder.create(name: "Disforia de Gênero em Crianças", description: "", disorder_group_id: 14)
Disorder.create(name: "Disforia de Gênero em Adolescentes e Adultos", description: "", disorder_group_id: 14)

Disorder.create(name: "Transtorno de Desafio Opositivo", description: "", disorder_group_id: 15)
Disorder.create(name: "Transtorno de Explosão Intermitente", description: "", disorder_group_id: 15)
Disorder.create(name: "Transtorno de Conduta", description: "", disorder_group_id: 15)
Disorder.create(name: "Transtorno de Personalidade Dissocial", description: "", disorder_group_id: 15)
Disorder.create(name: "Transtorno do Comportamento de Disrupção Sem Outra Especificação", description: "", disorder_group_id: 15)

Disorder.create(name: "Transtornos Associados ao Alcóol", description: "", disorder_group_id: 16)
Disorder.create(name: "Transtornos Associados à Cafeina", description: "", disorder_group_id: 16)
Disorder.create(name: "Transtornos Associados à Cannabis", description: "", disorder_group_id: 16)
Disorder.create(name: "Transtornos Associados a Alucinógenos", description: "", disorder_group_id: 16)
Disorder.create(name: "Transtornos Associados a Inalantes", description: "", disorder_group_id: 16)
Disorder.create(name: "Transtornos Associados a Opióides", description: "", disorder_group_id: 16)
Disorder.create(name: "Transtornos Associados a Sedativos/Hipnóticos", description: "", disorder_group_id: 16)
Disorder.create(name: "Transtornos Associados a Estimulantes", description: "", disorder_group_id: 16)
Disorder.create(name: "Transtornos Associados ao Tabaco", description: "", disorder_group_id: 16)
Disorder.create(name: "Transtornos Associados a Substâncias Desconhecidas", description: "", disorder_group_id: 16)
Disorder.create(name: "Transtornos de Jogo", description: "", disorder_group_id: 16)

Disorder.create(name: "Delirium", description: "", disorder_group_id: 17)
Disorder.create(name: "Transtorno Neurocognitivo Leve", description: "", disorder_group_id: 17)
Disorder.create(name: "Transtorno Neurocognitivo Maior", description: "", disorder_group_id: 17)

Disorder.create(name: "Transtorno da Personalidade Borderline", description: "", disorder_group_id: 18)
Disorder.create(name: "Transtorno da Personalidade Obsessivo-Compulsiva", description: "", disorder_group_id: 18)
Disorder.create(name: "Transtorno da Personalidade Aversiva", description: "", disorder_group_id: 18)
Disorder.create(name: "Transtorno da Personalidade Antissocial (Transtorno Dissocial da Personalidade)", description: "", disorder_group_id: 18)
Disorder.create(name: "Transtorno da Personalidade Narcísica", description: "", disorder_group_id: 18)
Disorder.create(name: "Transtorno da Personalidade com Traço Especificado", description: "", disorder_group_id: 18)

Disorder.create(name: "Transtorno Exibicionista", description: "", disorder_group_id: 19)
Disorder.create(name: "Transtorno Fetichista", description: "", disorder_group_id: 19)
Disorder.create(name: "Frotteurismo", description: "", disorder_group_id: 19)
Disorder.create(name: "Transtorno de Pedofilia", description: "", disorder_group_id: 19)
Disorder.create(name: "Transtorno de Masoquismo Sexual", description: "", disorder_group_id: 19)
Disorder.create(name: "Transtorno de Sadismo Sexual", description: "", disorder_group_id: 19)
Disorder.create(name: "Transtorno de Travestismo", description: "", disorder_group_id: 19)
Disorder.create(name: "Transtorno Voyeurístico", description: "", disorder_group_id: 19)
Disorder.create(name: "Transtorno de Parafilias Sem Outra Especificação", description: "", disorder_group_id: 19)

Disorder.create(name: "Lesões que Não São Auto Suicidas", description: "", disorder_group_id: 20)
Disorder.create(name: "Transtorno do Comportamento Suicida", description: "", disorder_group_id: 20)

puts "criando vídeos..."
Video.create(title: "Título do vídeo 1", description: "", link: '<iframe width="560" height="315" src="https://www.youtube.com/embed/J-nhV8KCUmU" frameborder="0" allowfullscreen></iframe>')
Video.create(title: "Título do vídeo 2", description: "", link: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Hc-kqzQBfQY" frameborder="0" allowfullscreen></iframe>')
Video.create(title: "Título do vídeo 3", description: "", link: '<iframe width="420" height="315" src="https://www.youtube.com/embed/YQSkej4mFpE" frameborder="0" allowfullscreen></iframe>')
Video.create(title: "Título do vídeo 4", description: "", link: '<iframe width="420" height="315" src="https://www.youtube.com/embed/03pyYiUChZs" frameborder="0" allowfullscreen></iframe>')
Video.create(title: "Título do vídeo 5", description: "", link: '<iframe width="420" height="315" src="https://www.youtube.com/embed/0uZL539clbQ" frameborder="0" allowfullscreen></iframe>')

puts "pronto!"